version: '2'
services:
      web:
        build: .
        ports:
          - "5000:5000"
        depends_on:
          - redis
      redis:
        image: redis
        ports:
          - "6379:6379"